### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND] on node.js v14 (ubuntu-latest)

### ISSUE THREAD

**Issue by aladdin-add** [iambumblehead/esmock#87] opened 2022-07-25 03:58 UTC
esmock@1.8.7
node: v14

you can see the github action log: https://github.com/eslint/create-config/runs/7493137743?check_suite_focus=true#step:5:12

**Comment by iambumblehead** [comment] 2022-07-25 04:04
adding a v14 CI pipeline in a new branch to see if the error shows up there

**Comment by iambumblehead** [comment] 2022-07-25 04:26
possibly the issue was introduced here https://github.com/iambumblehead/esmock/pull/68#issuecomment-1191884521

**Comment by aladdin-add** [comment] 2022-07-25 04:42
I pinned to `v1.7.x`, it seems working fine. https://github.com/eslint/create-config/pull/33/commits/e261c3f3c10c87416371d355fcc093f1050d68a9

**Comment by iambumblehead** [comment] 2022-07-25 04:55
@aladdin-add ok I'm relieved if you have a short-term solution.

If I touch one of the package.json files in esmock, the tests pass and I can't reproduce the error again. I wonder what the issue could be.

**Comment by iambumblehead** [comment] 2022-07-25 05:50
closing this because the v14 pipeline is passing and new sources are published

feel free to reopen for any reason

**Closed by iambumblehead** 2022-07-25 05:50 UTC

**Comment by aladdin-add** [comment] 2022-07-25 05:58
works for me. thx for the quick fix! 👍

**Comment by iambumblehead** [comment] 2022-07-25 06:00
thank you for sharing this issue with me and for helping me to improve this project
