### ISSUE TITLE
yarn pnp issues

### ISSUE THREAD

**Issue by koshic** [iambumblehead/esmock#241] opened 2023-09-08 11:23 UTC
Other scoped modules can't be mocked too. Wrong regexp?

Haven't enough time to provide unit test right now (

**Comment by iambumblehead** [comment] 2023-09-08 14:48
I will be able to take a look soon

**Comment by iambumblehead** [comment] 2023-09-08 15:02
@koshic if you have bandwidth, would you add a failing test in a PR? ideally, the test would be added to the [bottom of tests/tests-node/esmock.node.test.js](https://github.com/iambumblehead/esmock/blob/master/tests/tests-node/esmock.node.test.js#L508)

We could merge the failed-test PR right away and I could resolve the scope issue myself in a different branch.

**Comment by iambumblehead** [comment] 2023-09-08 16:18
> Haven't enough time to provide unit test right now (

Sorry I missed this not much sleep here. I'll add a test.

**Comment by iambumblehead** [comment] 2023-09-08 18:09
@koshic an @aws-sdk/client-s3 mock test is added here: https://github.com/iambumblehead/esmock/pull/242

The test passes. Would you help me to reproduce the issue? Maybe change the tests that are there or add a new test. I don't know how to reproduce the error.

**Comment by koshic** [comment] 2023-09-08 18:12
@iambumblehead sure, but tomorrow by Moscow time ) I was hoping to be free today, but...

**Comment by iambumblehead** [comment] 2023-09-08 18:15
@koshic no rush take your time :) https://www.youtube.com/watch?v=Lqg8_gpUm5A

**Comment by koshic** [comment] 2023-09-09 20:32
I'm here and will try to provide broken test / review other PRs

**Comment by koshic** [comment] 2023-09-10 13:45
@iambumblehead at first - thank you for creating branch and PR! My local example is very similar.

BTW, tests failed (github codespace, the same result on my local machine with node 20.6.1) after 'npm test':
<img width="908" alt="image" src="https://github.com/iambumblehead/esmock/assets/20106607/792f783a-909a-4e9d-93eb-5db0b8742a82">

It's a bit strange because on CI/CD both tests are passed:
<img width="623" alt="image" src="https://github.com/iambumblehead/esmock/assets/20106607/4ba23afa-9568-4ba2-9927-36b04461dfec">

**Comment by koshic** [comment] 2023-09-10 13:56
After 'npm install @aws-sdk/client-s3' in 'tests-node' dir errors were changed and now looks like errors in my project:
<img width="1079" alt="image" src="https://github.com/iambumblehead/esmock/assets/20106607/e5acabb4-1069-4127-a86f-0158f046fc77">

**Comment by iambumblehead** [comment] 2023-09-10 16:52
esmock does not support npm workspaces as mentioned in the other issue https://github.com/iambumblehead/esmock/issues/235#issuecomment-1709586126

Could that be the issue? 

That message is thrown when esmock [cannot locate the moduleId,](https://github.com/iambumblehead/esmock/blob/master/src/esmockModule.js#L128C1-L130C58) for example if the moduleId is found in a workspace esmock's resolver cannot lookup.
```javascript
const errModuleIdNotFound = (moduleId, parent) =>
  new Error(`invalid moduleId: "${moduleId}" (used by ${parent})`)
// ...
  const moduleFileURL = resolvewith(moduleId, parent)
  if (!moduleFileURL)
    throw esmockErr.errModuleIdNotFound(moduleId, parent)
```

Maybe try the suggestion from tpluscode added to the wiki https://github.com/iambumblehead/esmock/wiki#call-esmock-npm-workspaces

Maybe support for workspaces should be added to the resolver.

**Comment by koshic** [comment] 2023-09-10 17:43
Yeah , thx for that workaround - root cause is switching from import.meta.resolve to resolvewithplus, which is also doesn't support Yarn PnP.

**Comment by iambumblehead** [comment] 2023-09-12 00:05
@koshic I am trying to reproduce the "invalid moduleId" error, in order to update esmock so that workarounds will not be needed. Please give advice, if you know how the error could be reproduced.

Current tests which do not show the invalid moduleId error are here
  * https://github.com/iambumblehead/esmock/pull/243
  * https://github.com/iambumblehead/resolvewithplus/pull/46

**Comment by iambumblehead** [comment] 2023-09-13 03:46
@koshic when this other issue is resolved https://github.com/iambumblehead/esmock/issues/235 I'll spend time looking into this pnp issue

**Comment by iambumblehead** [comment] 2023-09-13 04:21
@koshic after running `npx yarn` the directory tree looks like this --where does yarn install resolvewithplus? Do you have any advice or recommendations for resolving this issue?
```bash
$ tree -a
.
├── .git
│   ├── HEAD
│   ├── branches
│   ├── config
│   ├── description
│   ├── hooks
│   │   ├── applypatch-msg.sample
│   │   ├── commit-msg.sample
│   │   ├── fsmonitor-watchman.sample
│   │   ├── post-update.sample
│   │   ├── pre-applypatch.sample
│   │   ├── pre-commit.sample
│   │   ├── pre-merge-commit.sample
│   │   ├── pre-push.sample
│   │   ├── pre-rebase.sample
│   │   ├── pre-receive.sample
│   │   ├── prepare-commit-msg.sample
│   │   ├── push-to-checkout.sample
│   │   ├── sendemail-validate.sample
│   │   └── update.sample
│   ├── index
│   ├── info
│   │   └── exclude
│   ├── logs
│   │   ├── HEAD
│   │   └── refs
│   │       ├── heads
│   │       │   └── main
│   │       └── remotes
│   │           └── origin
│   │               └── HEAD
│   ├── objects
│   │   ├── info
│   │   └── pack
│   │       ├── pack-0a5ec209d16661a258eb5787084d752e760c85bc.idx
│   │       ├── pack-0a5ec209d16661a258eb5787084d752e760c85bc.pack
│   │       └── pack-0a5ec209d16661a258eb5787084d752e760c85bc.rev
│   ├── packed-refs
│   └── refs
│       ├── heads
│       │   └── main
│       ├── remotes
│       │   └── origin
│       │       └── HEAD
│       └── tags
├── .gitignore
├── .pnp.cjs
├── .pnp.loader.mjs
├── .vscode
│   ├── extensions.json
│   └── settings.json
├── .yarn
│   ├── install-state.gz
│   ├── releases
│   │   └── yarn-4.0.0-rc.50.cjs
│   └── sdks
│       ├── integrations.yml
│       └── typescript
│           ├── bin
│           │   ├── tsc
│           │   └── tsserver
│           ├── lib
│           │   ├── tsc.js
│           │   ├── tsserver.js
│           │   ├── tsserverlibrary.js
│           │   └── typescript.js
│           └── package.json
├── .yarnrc.yml
├── README.md
├── package.json
├── packages
│   └── a
│       ├── package.json
│       └── test.js
└── yarn.lock
```

**Comment by iambumblehead** [comment] 2023-09-13 06:43
based on some investigation and on this discussion here https://github.com/wooorm/import-meta-resolve/issues/10 I am going to re-close this issue

**Closed by iambumblehead** 2023-09-13 06:43 UTC

**Comment by iambumblehead** [comment] 2023-09-13 08:32
if yarn pnp's module-resolving were refined to an npm package, other packages like esmock could use that to support pnp resolution. oh well, such a package does not exist.
