### ISSUE TITLE
import('node:fs/promises') called within a library does not seem to be replaced

### ISSUE THREAD

**Issue by btakita** [iambumblehead/esmock#281] opened 2023-12-22 02:45 UTC
I'm attempting to stub a call to `import('node:fs/promises')` called within a library. However, `esmock.p` global replacement does not seem to replace the call to `import(...)`. Is global replacements of `import(...)` covered in this library?

**Comment by iambumblehead** [comment] 2023-12-22 04:42
@btakita yes esmock is expected to mock global `import(moduleId)`

If you submit a reproduction failing test here it will probably be merged in the morning and used to develop a solution. If you don't want to submit a PR that's okay and I'll try and submit one over the next day or two.

**Comment by iambumblehead** [comment] 2023-12-22 06:43
@btakita when you have time would you take a look at this PR? https://github.com/iambumblehead/esmock/pull/282/files

> I'm attempting to stub a call to import('node:fs/promises') called within a library. 

Would you tell which library is used? Is it available on npm? Maybe that package could be used to replicate the exact situation causing the problem you are seeing.

**Comment by iambumblehead** [comment] 2023-12-22 06:48
@btakita this package uses `node:fs/promises` but doesn't suit the situation you decribed, because it does not use `await import('node:fs/promises')` and instead uses an import statement at the top of the file, https://www.npmjs.com/package/read-pkg

https://github.com/sindresorhus/read-pkg/blob/main/index.js#L2C25-L2C41

**Comment by btakita** [comment] 2023-12-23 02:54
Hi @iambumblehead...the [test in question](https://github.com/rebuildjs/rebuildjs/blob/main/browser/index.test.ts#L68) can be found in the `rebuildjs` package.

It uses the dependency `ctx-core` with [the implementation](https://github.com/ctx-core/ctx-core/blob/main/all/file_exists/index.js#L11-L12).

**Comment by iambumblehead** [comment] 2023-12-23 03:11
@btakita do you know why the test command fails for me? Help me run the rebuildjs tests

**Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@ctx-core/monorepo' **

```bash
rebuildjs$ npm test

> rebuildjs@0.20.7 test
> pnpm test-unit && check-dts


> rebuildjs@0.20.7 test-unit /home/bumble/software/rebuildjs
> NODE_OPTIONS=--loader=esmock tsx node_modules/uvu/bin.js . '\.test\.(ts|js)$'

(node:1069727) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("esmock", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1069741) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("esmock", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@ctx-core/monorepo' imported from /home/bumble/software/rebuildjs/build/index.js
    at packageResolve (node:internal/modules/esm/resolve:853:9)
    at moduleResolve (node:internal/modules/esm/resolve:910:20)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at nextResolve (node:internal/modules/esm/hooks:750:28)
    at d (file:///home/bumble/software/rebuildjs/node_modules/tsx/dist/esm/index.mjs:5:34)
    at O (file:///home/bumble/software/rebuildjs/node_modules/tsx/dist/esm/index.mjs:5:1187)
    at nextResolve (node:internal/modules/esm/hooks:750:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:238:30)
    at MessagePort.handleMessage (node:internal/modules/esm/worker:199:24)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:822:20)
 ELIFECYCLE  Command failed with exit code 1.
```

```bash
rebuildjs$ grep -ir @ctx-core ./build/
./build/index.js:import { writeFile } from '@ctx-core/monorepo'
```

**Comment by btakita** [comment] 2023-12-23 04:01
Sorry about that. My ide auto-imported the wrong module. If you pull, there should be a fix.

**Comment by btakita** [comment] 2023-12-23 04:18
If you want to change it yourself, it should be importing from `node:fs/promises`

**Comment by iambumblehead** [comment] 2023-12-23 06:08
@btakita maybe we/I could try making a smaller test around ctx-core however I believe esmock is working correctly in the recent version of rebuildjs cloned here.

To run the tests I did install ts-node and I'll explain that.  Running the test as-configured with tsx fails with useless runtime error and stacktrace details from minified sources.
```
Error: Parse error @:2:25
    at Ge (file:///home/bumble/software/rebuildjs/node_modules/tsx/dist/index-bd1ceb03.mjs:10:8007)
    at Xe (file:///home/bumble/software/rebuildjs/node_modules/tsx/dist/index-bd1ceb03.mjs:15:66)
    at Ie (file:///home/bumble/software/rebuildjs/node_modules/tsx/dist/index-bd1ceb03.mjs:15:297)
    at Z (file:///home/bumble/software/rebuildjs/node_modules/tsx/dist/esm/index.mjs:5:1900)
    at async nextLoad (node:internal/modules/esm/hooks:750:22)
    at async Hooks.load (node:internal/modules/esm/hooks:383:20)
    at async handleMessage (node:internal/modules/esm/worker:199:18)
```
Unfortunately, there seem to be issues with tsx. First, I cloned and installed tsx sources but the install process fails on node-gyp errors. tsx has never worked with esmock afaik https://github.com/iambumblehead/esmock/tree/main/tests/tests-FAIL-tsx here is an issue I reported at tsx and, when the issue was finally resolved, tsx still did not work correctly and failed with similar useless runtime error and minified source stacktrace.

---------------------------------------------------------------

A newer test-unit command was added to package.json, using ts-node and testing the single browser/index.test.ts file
```json
  "test-unit": "NODE_OPTIONS=--loader=ts-node/esm node_modules/uvu/bin.js . browser/index.test.ts"
```

The test file was updated to remove the `file_exists` stub
```diff
diff --git a/browser/index.test.ts b/browser/index.test.ts
index ff20ba3..19eaf81 100644
--- a/browser/index.test.ts
+++ b/browser/index.test.ts
@@ -57,15 +57,15 @@ test('browser__metafile', async ()=>{
                        browser__metafile__set: _browser__metafile__set,
                } = await esmock.p('./index.js', import.meta.url, {}, {
                        'ctx-core/rmemo': rmemo,
-                       'ctx-core/fs': {
-                               file_exists_: async (path:string)=>{
-                                       file_exists__path = path
-                                       return true
-                               }
-                       },
+                       //'ctx-core/fs': {
+                       //      file_exists_: async (path:string)=>{
+                       //              file_exists__path = path
+                       //              return true
+                       //      }
+                       //},
                        'node:fs/promises': {
                                // TODO: use this when https://github.com/iambumblehead/esmock/issues/281 is addressed
-                               // access: async ()=>{},
+                               access: async ()=> { 'test access!' },
                                readFile: async (path:string)=>{
                                        readFile_path = path
                                        switch (path) {
```

_ctx-core/all/file_exists/index.js_ was updated to log the access function String value
```javascript
	    && import('node:fs/promises').then(({ access, constants })=>{
                  console.log({ access: access.toString() })
		  return access(path, constants.F_OK)
				.then(()=>true)
				.catch(()=>false)
		}))
```

when the test fails, the correct access value is seen in the test process output
```bash
{
  access: "async () => {\n                    'test access!';\n                }"
}
✘ • •   (3 / 4)

   FAIL  "browser__metafile"
    Expected values to be deeply equal:  (equal)

        ++/cwd/dist0/browser/metafile.json  [string]     (Expected)
        --undefined                         [undefined]  (Actual)
```

Experimenting and adding more console.logs also shows the mocked readFile function is also used by the test.

SO I believe esmock is working there and if you disagree, I recommend submitting a PR with a test case that precisely surfaces the error using minimum number of files and vanilla javascript (unless typescript is a necessary part of reproducing the error)

**Comment by iambumblehead** [comment] 2023-12-23 07:10
_note_ tsx tests are passing [at the esmock test folder](https://github.com/iambumblehead/esmock/tree/main/tests/tests-FAIL-tsx) when the package.json is changed to use an esmock package version rather than filepath,
```json
  "dependencies": {
    "tsx": "^4.7.0",
-   "esmock": ".."
+   "esmock": "^2.6.0"
  },
```
possibly there is a bug in tsx's module resolution behaviour

**Comment by btakita** [comment] 2023-12-23 23:49
@iambumblehead Wow, thank you! I didn't consider tsx as the culprit. That makes sense. I'm traveling to visit family for the Christmas holidays. So I'll take a look at this when I have a moment over the next few days.

My tests are in ts to also perform type checking, so it would be nice to keep them that way if possible. I'll experiment with the different ts runners as well & let you know what I end up using. Thank you again!

**Comment by iambumblehead** [comment] 2023-12-24 03:13
Maybe the rebuildjs tests will pass and we can close this issue with that or maybe the ticket could close after a few weeks go by with no update...

Thanks for opening this issue and sharing rebuildjs and ctx-core.

**Comment by btakita** [comment] 2023-12-25 16:23
Hi @iambumblehead. I tried using esbuild & ran `node` on the built `.js` file, but have the same issue.

I made a branch `esmock/issues/281` on the esbuildjs repo with the reproduction. So I think tsx is unrelated to the issue.

**Comment by koshic** [comment] 2023-12-25 18:41
@btakita let's simplify that example a bit )

```js
// index.js
import { file_exists_ } from 'ctx-core/fs'

console.log('test file', (await import('node:fs/promises')).readFile)
```
```js
// node_modules/ctx-core/all/file_exists/index.js
console.log('file_exists_/index.js', (await import('node:fs/promises')).readFile)

export async function file_exists_() {
}
export {
	file_exists_ as path__exists_
}
export function file_exists__waitfor() {}
```
```js
// t.js
import esmock from 'esmock'

await esmock.p('./index.js', import.meta.url, {}, {
    'node:fs/promises': {
        readFile: 'NOT A FUNCTION'
    }
});
```
```shell
@koshic ➜ /workspaces/rebuildjs/browser (esmock/issues/281) $ node t.js 
file_exists_/index.js [AsyncFunction: readFile]
test file NOT A FUNCTION
```

As you can see, `(await import('node:fs/promises')).readFile` returns different result. So yes, it looks like `esmock` issue or really stupid issue with setup... @iambumblehead  what do you think?

**Comment by iambumblehead** [comment] 2023-12-26 08:07
The simplified version from @koshic is looking good. Possibly a fake package could be used inside an esmock test folder, and the fake package could include a similar `file_exists` function to reproduce the error with a test,
```json
  "dependencies": {
    "ctx-core-file-exists": "file:path/to/ctx-core-file-exists"
  }
```

If it works, things could be solved in two PRs,
 1. PR-1 reproduces the error with a failing test,
 2. PR-2 resolves the error so the test passes

Its midnight here and I'm busy tomorrow but will be available soon after. It looks like a good bug to resolve

**Comment by iambumblehead** [comment] 2023-12-26 08:14
`file:path/to/ctx-core-file-exists` ime node has difficulty handling this format inside package.json across platforms. The safest approach might be to use a single directory for the package...
```json
  "dependencies": {
    "ctx-core-file-exists": "file:ctx-core-file-exists"
  }
```

```bash
ctx-core-file-exists/
├── index.js
└── package.json
```
successfully getting the test to fail could be the most difficult part

**Comment by btakita** [comment] 2023-12-27 04:55
I was able to reproduce a successful stub with the `t.js` `esmock.p(`/path/to/file_exists_/index.js`, ...) directly, but not with `esmock.p(./index.js, ...)`.

Another thing about my environment that seems to differ from yours...I am running in a [pnpm monorepo with git submodules](https://github.com/ctx-core/dev). Perhaps the hard links from pnpm are causing an issue?

**Comment by btakita** [comment] 2023-12-27 05:18
I went ahead & pushed the dist directory to the `esmock/issues/281` branch, so we can run the same files. I also created a `esmock/issues/281` branch on the `ctx-core/ctx-core` & the `ctx-core/ctx-core-dev` repos. If you want to clone the `ctx-core/ctx-core-dev` repo, checkout the `esmock/issues/281` branch, then run:

```
git submodule init && git submodule update && pnpm i -r && pnpm prune && pnpm i -r
```

perhaps the environment with the test failure can be reproduced.

When I run

```
$ node /home/brian/work/ctx-core/ctx-core-dev/lib/rebuildjs/dist/browser/t.js
file_exists_/index.js {
  access: [AsyncFunction: access],
  readFile: [AsyncFunction: readFile]
}
```

**Comment by btakita** [comment] 2023-12-27 05:54
I created a `dist/browser/copy` directory which copies all dependency files in the SUT...so there are no symlinks or hard links. `t.js` importing `./copy/file_exists/index.js` also fails.

**Comment by iambumblehead** [comment] 2023-12-27 22:42
```bash
$ npx pnpm run test:unit

> rebuildjs@0.21.0 test:unit /home/bumble/software/rebuildjs
> NODE_OPTIONS=--loader=ts-node/esm node_modules/uvu/bin.js . browser/index.test.ts


node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ts-node' imported from /home/bumble/software/rebuildjs/
```
Its unclear how  to surface the problem. This would help,
 1. create a branch that surfaces the error; configure the branch such that as few changes and little explanation as possible are required to see the error,
 2. in the branch created to demonstrate the error, define a script command in the package.json that runs one single test which reproduces the error,
 3. list specific and complete directions that can be followed to  install, build and/or run the unit tests.  If pnpm is used for installing or running the tests, the necessary pnpm commands should be shown in the reproduction steps. Provide directions in a compact list which can easily be followed by anyone

**Comment by btakita** [comment] 2023-12-28 06:43
I reproduced the issue with npm in https://github.com/btakita/esmock-issues-281

```
$: node -v
v20.10.0
$: uname -mprs
Linux 6.6.8-arch1-1 x86_64 unknown
```

**Comment by btakita** [comment] 2023-12-28 18:25
If you are unable to reproduce, I can debug when some of my work clears up. Since the `import` function is async, is it possible that the loader is resetting too early?

**Comment by iambumblehead** [comment] 2023-12-28 18:33
The reproduction repo is good and I'm able to reproduce the problem there

Thank you

**Comment by iambumblehead** [comment] 2023-12-28 19:31
The repro esmock call should define the mock globally using the third param, however, even after making that change the imported value is not mocked. I can see that the esmock loader is completely skipping node:fs/promises but I'm not sure why. 

I'll try copying things to an esmock test, so easier to compare with existing tests and to be sure any changes made won't break existing behaviour.

**Comment by iambumblehead** [comment] 2023-12-28 19:47
I think this is reproduced in the unit-tests now... mocking a "builtin" node module globally seems to be the main issue.

**Comment by iambumblehead** [comment] 2023-12-28 21:27
@btakita this looks like an upsteam nodejs bug, my findings and a suggested work-around are given below.

When the node's resolver hook resolves the async-imported 'node:fs/promises', the parent url is missing the query string that holds the mock details. Using console.log shows the resolver hook returns this `resolved.url` for "usesInlineBuiltinImport.js"
```bash
file:///home/bumble/software/esmock/tests/local/usesInlineBuiltinImport.js?esmkgdefs=node:fs/promises?[...]
```
but when `node:fs/promises` is async imported, the resolver hook is called with a `context.parentURL` that is missing the query string and without the query string esmock is unable to alter the behaviour
```bash
file:///home/bumble/software/esmock/tests/local/usesInlineBuiltinImport.js
```

I believe this is an upstream nodejs bug. If we want upstream nodejs to look into this, we'll need to make a small test case for that (I could do this) and there are no guarantees we can expect any changes there.

Until a solution happens... try nesting locally mocked `node:fs/promises` inside globally mocked modules like this for now (the below pattern results in a passing test here)
```javascript
const main = await esmock.p('../local/usesInlineBuiltinImportChild.js', {}, {
  '../local/usesInlineBuiltinImport.js': (
    await esmock.p('../local/usesInlineBuiltinImport.js', {
      'node:fs/promises': {
        readdir: () => (['mock', 'global'])
      }
    }))
})
```

**Comment by iambumblehead** [comment] 2023-12-28 22:48
I tried making a small reproduction, but tests here pass https://github.com/iambumblehead/nodejs-resolve-hook-incomplete-parenturl-async-builtin-import

I'm not sure why parentURL is correct at the demonstration, but incorrect at our unit -test.

**Comment by iambumblehead** [comment] 2023-12-28 23:39
The test is passing locally... looking into it further revealed that esmock itself was stripping the querystring from the url

A solution can probably be pushed up tonight or tomorrow.

**Comment by iambumblehead** [comment] 2023-12-29 02:46
@btakita a solution is here https://github.com/iambumblehead/esmock/pull/282

**Comment by btakita** [comment] 2023-12-29 08:33
Thank you! This will be a big help in consolidating my libraries, as it will be easier to test isomorphic code.

**Comment by iambumblehead** [comment] 2024-01-14 03:41
closing with this https://github.com/iambumblehead/esmock/pull/282

will publish shortly

**Closed by iambumblehead** 2024-01-14 03:41 UTC
