### ISSUE TITLE
Partial mocking not working as expected

### ISSUE THREAD

**Issue by re-kfa** [iambumblehead/esmock#186] opened 2022-11-22 15:20 UTC
Hi,
I'm trying to partially mock an imported module, but esmock seems to mock the whole module so that functions which I don't want to mock are not available.

app.js:
```
import express from "express";
import passport from "passport";

const app = express();
const bearerOptions = { ... };

passport.use(bearerStrategy);
app.use(passport.initialize());
```

app.test.js:
```
import chai from "chai";
import chaiHttp from "chai-http";
import esmock from "esmock";

chai.use(chaiHttp);
chai.should();

const app = await esmock(
	"../src/app.js",
	{
		passport: {
			use: function (bearerStrategy) {
				console.log(bearerStrategy);
			},
		},
	},
	{}
);

describe("/", function () {
	it("should work", (done) => {
		try {
			chai
				.request(app.default)
				.get("/")
				.end((err, res) => {
					try {
						res.should.have.status(200);
					} catch (err) {
						console.error(res.text);
						throw err;
					}
					done();
				});
		} catch (e) {
			console.log(e);
		}
	});
});
```

Expected result:
Output from mocked passport.use method and **call of original passport.initialize method**

Actual result:
`TypeError: passport.initialize is not a function
    at file:///C:/../src/app.js?esmk=1:9:18
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async file:///C:/.../node_modules/esmock/src/esmock.js:3:176
    at async file:///C:/.../tests/app.test.js:11:13`

What am I doing wrong here?

Thanks!

**Comment by iambumblehead** [comment] 2022-11-22 16:53
@re-kfa try this and if it doesn't work, we'll use a unit test for your example and make it work
```diff
const app = await esmock(
	"../src/app.js",
	{
		passport: {
-			use: function (bearerStrategy) {
-				console.log(bearerStrategy);
-			},
+			default: {
+				use: function (bearerStrategy) {
+						console.log(bearerStrategy);
+				},
+			},
		},
	},
	{}
);
```

**Comment by re-kfa** [comment] 2022-11-25 13:55
@iambumblehead thanks for your answer. unfortunately it is not working. same error as before.
What do you mean by "adding a unit-test"?

**Comment by mshima** [comment] 2022-11-25 18:39
I got hit by this problem.
Looks related with `resolvewithplus` at windows.
Enabling `--experimental-import-meta-resolve` fixes the problem.

**Comment by iambumblehead** [comment] 2022-11-25 20:22
the issue is reproduced here now https://github.com/iambumblehead/esmock/pull/188

**Comment by iambumblehead** [comment] 2022-11-25 20:38
the issue is here specifically https://github.com/iambumblehead/esmock/blob/master/src/esmockModule.js#L21-L22

esmock is assigning passport's "class instance" default export with the mock object onto a new object. Maybe we should try adding the class instance into the prototype chain of the resulting object.

**Comment by iambumblehead** [comment] 2022-11-25 20:40
this resolves the isue
```diff
 const esmockModuleMergeDefault = (defLive, def) =>
-  (isObj(defLive) && isObj(def)) ? Object.assign({}, defLive, def) : def
+  (isObj(defLive) && isObj(def)) ? Object.assign(Object.create(defLive), def) : def
```

**Comment by mshima** [comment] 2022-11-25 20:56
Took another looks and I think I had another issue.
```
"before each" hook for "provide default options":
[522](https://github.com/mshima/generator/actions/runs/3550032234/jobs/5963163423#step:5:523)
     Error: invalid moduleId: "execa" (used by file:///D:/a/generator/generator/test/spawn-command.js)
      at Object.ye [as errModuleIdNotFound] (file:///D:/a/generator/generator/node_modules/esmock/src/esmock.js:1:61)
      at A (file:///D:/a/generator/generator/node_modules/esmock/src/esmock.js:2:5391)
      at dt (file:///D:/a/generator/generator/node_modules/esmock/src/esmock.js:2:5719)
      at file:///D:/a/generator/generator/node_modules/esmock/src/esmock.js:3:161
      at async Context.<anonymous> (file:///D:/a/generator/generator/test/spawn-command.js:13:18)
```

Using:
```
await esmock('../lib/actions/spawn-command', {
  execa: {
    execa: sinon.spy(),
    execaSync: sinon.spy(),
  },
});
```

Unfortunately I don't have a window machine to try to reproduce.

**Comment by iambumblehead** [comment] 2022-11-25 21:03
@mshima would you open a separate issue for that? when the moduleId not found error is seen, are you using --experimental-import-meta-resolve?

I think the original issue described in this ticket is resolved in my local branch. We'll need to publish a new version of esmock to resolve.

**Comment by iambumblehead** [comment] 2022-11-25 21:08
@mshima both this repo and the resolvewithplus repo have windows-latest pipelines and we can use those to reproduce (feel free to add a unit-test to a PR). Also I have windows virtual machine setup here that I can use.

**Comment by mshima** [comment] 2022-11-25 21:15
> @mshima would you open a separate issue for that? when the moduleId not found error is seen, are you using --experimental-import-meta-resolve? are you using a transpiler?

@iambumblehead thanks for the help.
The `the moduleId not found` error  is seen when `--experimental-import-meta-resolve` disabled.
No transpiler.

The error can be seen at https://github.com/mshima/generator/actions/runs/3549888418/jobs/5962747660.

> @mshima both this repo and the resolvewithplus repo have windows-latest pipelines

I saw that. I was trying so see if the fix was obvious.

**Comment by iambumblehead** [comment] 2022-11-25 21:18
@mshima if you [PR-add a failing test,][0] I will merge it and try to resolve in a separate branch. Add the test to one of the test runner folders [here][0]. From esmock's root folder use `npm install && npm run test:install` to fetch all dependencies needed, then from whichever test folder is being used, `npm test` will run tests.

If you don't add a failing test that is okay also of course but it might take a little longer to resolve

[0]: https://github.com/iambumblehead/esmock/tree/master/tests
[1]: https://github.com/iambumblehead/esmock/blob/master/src/esmockModule.js#L57-L63

**Comment by mshima** [comment] 2022-11-25 21:19
The repository is https://github.com/mshima/generator/commits/esm.
Removing the experimental flag from .mocharc.cjs should trigger the problem.
In any case it's working now. So the priority is low.

**Comment by mshima** [comment] 2022-11-25 21:21
I would love to help more, but I am quite busy.

**Comment by iambumblehead** [comment] 2022-11-25 21:50
https://github.com/iambumblehead/resolvewithplus/pull/41/files I tried reproducing the issue at the scripted resolver and the test there passes. I'll need to try using esmock to more closely match the situation at pipeline you linked...

github pipelines are moving slowly today :/

**Comment by mshima** [comment] 2022-11-25 22:17
I realized it’s missing the extension:
https://github.com/mshima/generator/blob/8af2d2b40c1a2af9cc3a26b27dd1b5a69046f752/test/spawn-command.js#L13
I will test when in front of a computer again.

**Comment by iambumblehead** [comment] 2022-11-25 22:28
@mshima good catch. I'm not sure if esmock should be updated in any way for this feel to give your opinion. I did clone your esm branch into the windows virtual machine I use...

**Comment by mshima** [comment] 2022-11-25 23:05
Update the extension is missing but it's wrapped at a `require.resolve` ([added to test](https://github.com/mshima/generator/commit/aa402472b1882714dec2631b193664fb8aa6c2a2) if fixes the problem).
So the end result have the extension.

**Comment by iambumblehead** [comment] 2022-11-25 23:26
this issue should be resolved with this PR https://github.com/iambumblehead/esmock/pull/188 and esmock@2.0.8 will be published soon --feel free to re-open if the issue is not resolved or for any other reason probably

**Closed by iambumblehead** 2022-11-25 23:26 UTC
