### ISSUE TITLE
`invalid moduleId` error when using tsx

### ISSUE THREAD

**Issue by tommy-mitchell** [iambumblehead/esmock#209] opened 2023-07-09 23:20 UTC
I'm trying to use `esmock` with AVA and TypeScript via transpilation with [`tsx`](https://github.com/esbuild-kit/tsx) (i.e. `esbuild`) on Node.js v18.16.1. My loader chain is effectively

```sh
node --loader=tsx --loader=esmock
```

<details>
<summary>AVA configuration</summary>

```json
"files": [
	"test/*.ts"
],
"extensions": {
	"ts": "module"
},
"nodeArguments": [
	"--loader=tsx",
	"--loader=esmock",
	"--no-warnings=ExperimentalWarning"
]
```

</details>

<details>
<summary>Project structure</summary>

```
\__ src/
	\__ source-file.ts
\__ test/
    \__ test-file.ts
\__ package.json
\__ tsconfig.json
```

</details>

When trying to mock my source file, I get an `invalid moduleId` error:

```ts
// test/test-file.ts

import test from "ava";
import esmock from "esmock";

test("with mock", async t => {
	const { setExecutableBits } = await esmock("../src/source-file.js", import.meta.url, {
		// ...
	}) as typeof import("../src/source-file.js");

	// ...
});
```

```
Rejected promise returned by test. Reason:

  Error {
    message: 'invalid moduleId: "../src/source-file.js" (used by file:///.../test/test-file.ts)',
  }

  › Object.$e (node_modules/esmock/src/esmock.js:1:61)
  › wt (node_modules/esmock/src/esmock.js:2:6113)
  › <anonymous> (node_modules/esmock/src/esmock.js:3:161)
```

Am I missing something?

**Comment by iambumblehead** [comment] 2023-07-10 05:26
There's not an esmock tsx test and it would be great to have one. Feel free to submit a PR, otherwise I'll respond in a week or so with a solution.

related, 
 * current tests folders https://github.com/iambumblehead/esmock/tree/master/tests
 * https://github.com/iambumblehead/esmock/blob/master/CONTRIBUTING.md

**Comment by iambumblehead** [comment] 2023-07-10 05:34
it would be awesome if you would submit a PR with a failing test

**Comment by tommy-mitchell** [comment] 2023-07-10 14:44
Added failing tests at #210.

**Comment by iambumblehead** [comment] 2023-07-10 19:19
@tommy-mitchell thank you for the test cases. Possibly related, ava is not fully compatible with esm --loader
 * https://github.com/avajs/ava/issues/3195
 * https://github.com/avajs/ava/issues/3211

Will take a look later this evening

**Comment by iambumblehead** [comment] 2023-07-11 04:54
this seems to come from a configuration issue, such as the configurations discussed here https://stackoverflow.com/questions/62096269/cant-run-my-node-js-typescript-project-typeerror-err-unknown-file-extension

the error occurs [at this line,](https://github.com/iambumblehead/esmock/blob/master/src/esmock.js#L12C3-L12C50) where importing the ts file causes the error 
```javascript
const importedModule = await import(fileURLKey)
//   TypeError {
//     code: 'ERR_UNKNOWN_FILE_EXTENSION',
//     message: 'Unknown file extension ".ts" for /home/bumble/software/esmock/tests/local/main.ts',
```
I'm not great at setting up configurations for things like this but will keep trying a little bit

**Comment by iambumblehead** [comment] 2023-07-11 04:57
PR is here https://github.com/iambumblehead/esmock/pull/211

**Comment by iambumblehead** [comment] 2023-07-11 05:01
this issue seems related https://github.com/avajs/ava/issues/2593#issuecomment-1524846453

**Comment by tommy-mitchell** [comment] 2023-07-11 05:22
Potentially related too: https://github.com/avajs/ava/discussions/3213#discussioncomment-6315510

**Comment by iambumblehead** [comment] 2023-07-11 05:50
these results indicate the problem may come from tsx,
 * **if tsx is used, the tests fail** if either `node:test` or `ava` are used as the test runner
 * **if ts-node/esm is used, the tests pass** if either `node:test` or `ava` are used as the test runner

I'll push up some changes to the PR that make it a little easier to switch between the two transpilers and test-runners

**Comment by iambumblehead** [comment] 2023-07-11 06:01
At the PR, I removed the invalid moduleId test, because the moduleId was actually invalid (the file path being imported did not exist) and it esmock is expected to throw an error in that situation. That is separate from the unknown-file-extension-error which seems to be a real issue.

**Comment by iambumblehead** [comment] 2023-07-11 18:07
@tommy-mitchell I think I've narrowed down the issue to something that could be used to submit an issue at the tsx project,
```javascript
test('tsx should not break when import paths include query params', async () => {
  assert.ok(await import('../local/main.ts?n=4'))
})
```
when query params are removed, the above test passes

**Comment by tommy-mitchell** [comment] 2023-07-11 18:56
Nice find.

**Comment by iambumblehead** [comment] 2023-07-28 17:21
Closing with this https://github.com/iambumblehead/esmock/pull/211

A tsx note is embedded to the README scripts example. Feel free to reopen for any reason.

**Closed by iambumblehead** 2023-07-28 17:21 UTC

**Comment by tonisives** [comment] 2023-09-14 01:01
I get the same invalid moduleId error for `node --loader=ts-node/esm src/simpletest.test.ts`

```
import { test } from "uvu"
import esmock from "esmock"
import { myFun } from "./simpletest.js"


test("test not real", async () => {
  let mock = await esmock("./simpletest.js", {
    myFun: () => console.log("mocked")
  })
  
  myFun()
})


test.run()
```

```
export const myFun = () => {
  console.log("still real");
}
```


```
➜ node --loader=ts-node/esm src/simpletest.test.ts
(node:5062) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
✘   (0 / 1)

   FAIL  "test not real"
    invalid moduleId: "myFun" (used by file:///Users/tonis/workspace/js/audit-hero/parsers/packages/findings/src/simpletest.test.ts)
```

uvu runner
"ts-node": "^10.9.1",
node 20.6.1
"uvu": "^0.5.6"

**Comment by iambumblehead** [comment] 2023-09-14 01:09
@tonisives I'll setup a local reproduction with samples you gave. Are you using the latest esmock published an hour or two ago?

**Comment by iambumblehead** [comment] 2023-09-14 01:32
@tonisives respectfully, the example you gave probably does not use esmock correctly. Call esmock to mock values that are imported by the target module. See this diff, for example, which results in a passing test using the two files attached further below.
```diff
diff --git a/src/simpletest.test.ts b/src/simpletest.test.ts
index a1633c6..13a3370 100644
--- a/src/simpletest.test.ts
+++ b/src/simpletest.test.ts
@@ -1,13 +1,14 @@
 import { test } from "uvu"
 import esmock from "esmock"
-import { myFun } from "./simpletest.js"
+import simpletest from "./simpletest.js"
 
 test("test not real", async () => {
   let mock = await esmock("./simpletest.js", {
-    myFun: () => console.log("mocked")
+    "./simplefunctions.js": { myFun: () => console.log("mocked") }
   })
-  
-  myFun()
+
+  mock()
+  simpletest()
 })
 
 test.run()
```

_src/simplefunctions.ts_
```javascript
export const myFun = () => {
  console.log("still real");
}
```

_src/simpletest.js_
```javascript
import { myFun } from './simplefunctions.js'

export default myFun
```
